version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - HOST_URL=http://server:8080/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/test"]
      interval: 5s
      timeout: 3s
      retries: 5


  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      server:
        condition: service_healthy
